#ifndef PET_PASSAGE_PORTS_H_
#define PET_PASSAGE_PORTS_H_

#define FRONT_MAG_PORT 12
#define BACK_MAG_PORT 13

#define CLOSED_LED_PORT 2
#define OPEN_IN_LED_PORT 4
#define OPEN_OUT_LED_PORT 3
#define ERROR_LED_PORT 5

#endif
